### ISSUE TITLE
Non-critical resource not deferred?

### ISSUE THREAD

**Issue by kosiew** [Automattic/page-optimize#40]
Customer in #2958384-zen says the his site is not doing well on mobile.

Specifically, he mentioned that some non-critical resources are loading and slowing the first paint.

He provided the screenshot at:
https://disruptable.net/wp-content/uploads/2020/05/google-inspection.png
and Google's recommendation at 
https://disruptable.net/wp-content/uploads/2020/05/Google-speed-test-recomendation-noted-with-worpress-2.png

Customer's goal is to improve the site performance on mobile.

Is Customer's analysis correct 

Is there a way to eliminate/defer unused resources?

**Comment by brandonpayton** [comment]
Hi @koseiw,

It is difficult for us to determine what are critical and non-critical resources, and page-optimize has limited, simple behavior. If there is unused CSS, it may be truly unused or else added by plugins because it is used in certain cases.

It's possible page-optimize could be made to do more, but honestly, I think it will be a lot of effort for less reward.

The advice provided by the Google in their screenshot is roughly what I was writing in response until I noticed Google suggesting the same things. Those are the things I would try.
